[mailgun]
api_base_url = "https://api.mailgun.net/v3/email.b01lers.com"
email_address = "Purdue Capture The Flag Team <b01lers@b01lers.com>"

[server]
guild_id = 1073454690081181716

ctf_category_id = 1277386385002594304
archived_ctf_category_id = 1277386436164845639
solve_approvals_channel_id = 1277386525205725306
bot_log_channel = 1277386853460476048
rank_up_channel = 1277386889149808662

officer_role = "officer"
member_role = "members"

[ranks]
points_per_solve = 100
points_per_message = 1

rank_names = [
    "rank1",
    "rank2",
    "rank3",
    "rank4",
    "rank5",
]